### ISSUE TITLE
Disabling the parent option causes errors

### ISSUE THREAD

**Issue by riversdev0** [wadmiraal/jquery-tabledrag#2]
I attempted to disable the parent option by passing the following option string to the tableDrag function:
`{parent: {fieldClass: false, sourceFieldClass: 'person-id',hidden: true}}`
and it produced the following javascript error when I dragged a row:
`Uncaught TypeError: Cannot read property 'relationship' of undefined`
I attempted `undefined` and `null` as well, but the results were the same.

**Comment by wadmiraal** [comment]
So sorry for my extremely late reply. I don't know why, I never got notified for this issue (or I did, and completely forgot about it). So, it is fixed. Better late than never...
