### ISSUE TITLE
Depth issue

### ISSUE THREAD

**Issue by rutcreate** [wadmiraal/jquery-tabledrag#6]
I have tried to debug depth values and I got wrong values.

Step to reproduce:

- Open http://wadmiraal.github.io/jquery-tabledrag/
- Open javascript console.
- Run `$('.row-depth').eq(0).val();, $('.row-depth').eq(1).val();, $('.row-depth').eq(2).val();` you will get values 1, 2, 1 as expected.
- Move Candice below Bob and run command above again, you will get 1, 2, 1 instead of 1, 2, 2

**Comment by wadmiraal** [comment]
Wait, no, that didn't fix it :-).

**Comment by rutcreate** [comment]
Oh, thanks! but I just created my own jquery plugin with latest version of tabledrag.js from Drupal7. It seems quite a bit difference from your version.

**Comment by wadmiraal** [comment]
Possible. The fork was made in 2013. Drupal 7 has changed during that time. But it it based on Drupal 7. Most of it should be fairly similar.

**Comment by rutcreate** [comment]
Yes! you are right. The big difference is the latest version has no column (dropdown select) column and definitely the options but it is not a big deal.
